---
## Deploy Spark Operator

- name: Install openshift python lib
  pip:
    name: openshift
    extra_args: --user

- name: Prepare operator manifest
  template:
    src: operator.j2
    dest: operator.yaml

- name: Deploy the operator from the manifest
  k8s_raw:
    state: present
    src: operator.yaml

- block:
    - name: Ensure we are system:admin (1)
      shell: oc whoami | grep "system:admin" || kubectl config current-context | grep "system:admin"
      ignore_errors: yes
      changed_when: false
      register: whoami_result

    - name: Ensure we are system:admin (2)
      fail:
        msg: In order to be able to deploy the Prometheus, we need to be logged in as system:admin. Do that using oc or kubectl.
      when: whoami_result.rc != 0

    - name: Prepare Prometheus operator manifest
      template:
        src: prometheus-operator.j2
        dest: prometheus-operator.yaml

    - name: Deploy Prometheus operator
      k8s_raw:
        state: present
        src: prometheus-operator.yaml

    - name: Wait 10 seconds for the CRDs
      wait_for: timeout=10
      when: runExampleCluster

  when: prometheus

- block:
    - name: Set correct file path for example cluster
      set_fact:
        example_file: "example{% if prometheus %}-metrics{% endif %}{% if crd %}-cr{% endif %}"

    - name: Print the path
      debug:
        msg: "We will be using '{{ example_file }}.j2' template."

    - name: Template for example cluster
      template:
        src: "{{ example_file }}.j2"
        dest: "{{ example_file }}.yaml"

    - name: Deploy example cluster
      k8s_raw:
        state: present
        src: "{{ example_file }}.yaml"

    # - name: Expose Prometheus service
    #   k8s_raw: todo

  when: runExampleCluster